### ISSUE TITLE
make websafe_svg windows supported

### ISSUE THREAD

**Issue by rupamking1** [peiffer-innovations/websafe_svg#10]
make websafe_svg windows supported

**Comment by jpeiffer** [comment]
You'll need to check with the maintainer of [flutter_svg](https://pub.dev/packages/flutter_svg) as this project utilizes that for all `dart:io` based platforms: Android, iOS, Linux, Windows, MacOS.

I _believe_ Windows already works with that project, which if so, would mean it works here too.  But I have no Windows computers on which I could actually validate that.  Either way, this request is outside the scope of this plugin.
