### ISSUE TITLE
Unable to load asset: First/Pricing0.svg 

### ISSUE THREAD

**Issue by rupamking1** [peiffer-innovations/websafe_svg#11]
The following assertion was thrown resolving a single-frame picture stream:
Unable to load asset: First/Pricing0.svg

When the exception was thrown, this was the stack
#0      PlatformAssetBundle.load 
package:flutter/…/services/asset_bundle.dart:225
<asynchronous suspension>
#1      AssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:68
#2      CachingAssetBundle.loadString.<anonymous closure> 
package:flutter/…/services/asset_bundle.dart:166
#3      _LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:291:23))
...
Picture provider: ExactAssetPicture(name: "First/Pricing0.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#1d168(), name: "First/Pricing0.svg", colorFilter: null)
════════════════════════════════════════════════════════════════════════════════

I checked 5 times web and android also, but still error.
please help me.

**Comment by rupamking1** [comment]
I think made for this dollar      id="$-5"    
I already tried in String.

**Comment by jpeiffer** [comment]
I don't think I've ever worked with the ExactAssetPicture before.  Would it be possible to create a full repo showing the problem?  Otherwise, I don't really know how to begin trying to help with this particular one, especially since the stack trace provided doesn't even reference any code from this project.

**Comment by rupamking1** [comment]
I already find the solution. in Svg jhing I used $ symbol for that reason its make dart error.
