### ISSUE TITLE
SVG shadow not showing in Android

### ISSUE THREAD

**Issue by rupamking1** [peiffer-innovations/websafe_svg#12]
SVG shadow not showing in Android how to fix it.

**Comment by rupamking1** [comment]
Please help me 
SVG shadow not showing in Android but showing in web, how to fix it.

**Comment by jpeiffer** [comment]
On Android, this utilizes the awesome flutter_svg package for the actual rendering.  This package is just a thin wrapper that determines whether to use that package or web native for rendering the SVG.

You'll have to open an issue here: https://github.com/dnfield/flutter_svg/issues
