### ISSUE TITLE
New project using dev channel failed to build

### ISSUE THREAD

**Issue by npjonath** [peiffer-innovations/websafe_svg#16]
Something goes wrong when building on ios a fresh project using this library. (websafe_svg: ^1.1.4+2)

Error happen when running this command on fresh project and adding this library : 
`
flutter run -d <ios-device-id>
`

Error Message :
`
  ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.2+1/lib/src/picture_provider.dart:57:59: Error: No named
    parameter with the name 'nullOk'.
            context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                              ^^^^^^
    ../../development/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments
    don't match.
      static Locale localeOf(BuildContext context) {
                    ^^^^^^^^
`

Expected behavior :
Build correctly and launch the app.

Possible solution : 
Require to update dependencies to flutter_svg: ^0.20.0-nullsafety.3

**Comment by vixez** [comment]
Yes, please update the dependency.
I can't update to the new Flutter version because of this.

**Comment by tjerkw** [comment]
Same problem here. Lots of things in flutter are falling apart due to this nullsafety update.

**Comment by jpeiffer** [comment]
Closing issue as Flutter 2 is now stable, and the latest pre-release is now fully Null Safe.
