### ISSUE TITLE
Exception caught by image resource service

### ISSUE THREAD

**Issue by BeliliFahem** [peiffer-innovations/websafe_svg#17]
Since updating flutter web to 1.26.0-17.5.pre (channel Beta), SVGs are no longer visible and I have the **following error** : 

`
The following ImageCodecException was thrown resolving an image codec:
Failed to decode image data.
Image source: data:image/svg+xml;base64,
PHN2ZyBpZD0iQ29tcG9zYW50XzJfMSIgZGF0YS1uYW1lPSJDb21wb3NhbnQgMiDigJMgMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTU2IgogICAgaGVpZ2h0PSI1MiIgdmlld0JveD0iMCAwIDE1NiA1MiI+CiAgICA8ZyBpZD0iVW5pb25fMiIgZGF0YS1uYW1lPSJVbmlvbiAyIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg3NCAxMCkiIGZpbGw9Im5vbmUiPgogICAgICAgIDxwYXRoIGQ9Ik0yMy41ODQsMzkuMDMxLDE5LjksMzIuNjVhMTYuNSwxNi41LDAsMSwxLDUuNTkzLTIuMzEzbDMuMjg3LDUuNjk0YTMsMywwLDEsMS01LjIsM1oiCiAgICAgICAgICAgIHN0cm9rZT0ibm9uZSIgLz4KICAgICAgICA8cGF0aAogICAgICAgICAgICBkPSJNIDE2LjQ5OTcwMDU0NjI2NDY1IDI2LjAwMDMwMzI2ODQzMjYyIEMgMTcuMTYzMzc1ODU0NDkyMTkgMjYuMDAwMzAzMjY4NDMyNjIgMTcuODI0MzAwNzY1OTkxMjEgMjUuOTMyMzc4NzY4OTIwOSAxOC40NjQwODg0Mzk5NDE0MSAyNS43OTg0MDI3ODYyNTQ4OCBMIDIwLjE4ODQzNjUwODE3ODcxIDI1LjQzNzMxMzA3OTgzMzk4IEwgMjEuNjcyNDYyNDYzMzc4OTEgMjQuNDcxMDc4ODcyNjgwNjYgQyAyNC4zODI0MTM4NjQxMzU3NCAyMi43MDY2NDAyNDM1MzAyNyAyNi4wMDAzMDEzNjEwODM5OCAxOS43MjY2OTAyOTIzNTg0IDI2LjAwMDMwMTM2MTA4Mzk4IDE2LjQ5OTcwMjQ1MzYxMzI4IEMgMjYuMDAwMzAxMzYxMDgzOTggMTEuMjYxNTUzNzY0MzQzMjYgMjEuNzM4MzQ5OTE0NTUwNzggNy4wMDAwMDMzMzc4NjAxMDcgMTYuNDk5NzAwNTQ2MjY0NjUgNy4wMDAwMDMzMzc4NjAxMDcgQyAxMS4yNjE1NTA5MDMzMjAzMSA3LjAwMDAwMzMzNzg2MDEwNyA3LjAwMDAwMDQ3NjgzNzE1OCAxMS4yNjE1NTM3NjQzNDMyNiA3LjAwMDAwMDQ3NjgzNzE1OCAxNi40OTk3MDI0NTM2MTMyOCBDIDcuMDAwMDAwNDc2ODM3MTU4IDIxLjczODM1MzcyOTI0ODA1IDExLjI2MTU1MDkwMzMyMDMxIDI2LjAwMDMwMzI2ODQzMjYyIDE2LjQ5OTcwMDU0NjI2NDY1IDI2LjAwMDMwMzI2ODQzMjYyIE0gMjYuMTg0NTM3ODg3NTczMjQgNDAuNTMyMjY0NzA5NDcyNjYgQyAyNS4xNDc2MDAxNzM5NTAyIDQwLjUzMjMwMjg1NjQ0NTMxIDI0LjEzOTA1MTQzNzM3NzkzIDM5Ljk5NDE5MDIxNjA2NDQ1IDIzLjU4MzYwMDk5NzkyNDggMzkuMDMxMjA0MjIzNjMyODEgTCAxOS44OTg3OTk4OTYyNDAyMyAzMi42NDk3OTE3MTc1MjkzIEMgMTguODAxNzYzNTM0NTQ1OSAzMi44Nzk1MTY2MDE1NjI1IDE3LjY2NTAxMjM1OTYxOTE0IDMzLjAwMDMwNTE3NTc4MTI1IDE2LjQ5OTcwMDU0NjI2NDY1IDMzLjAwMDMwNTE3NTc4MTI1IEMgNy4zODcyMDA4MzIzNjY5NDMgMzMuMDAwMzA1MTc1NzgxMjUgNi44MDU0MTk3Mjk5NzE2MThlLTA3IDI1LjYxMzEwMzg2NjU3NzE1IDYuODA1NDE5NzI5OTcxNjE4ZS0wNyAxNi40OTk3MDI0NTM2MTMyOCBDIDYuODA1NDE5NzI5OTcxNjE4ZS0wNyA3LjM4NzIwMzIxNjU1MjczNCA3LjM4NzIwMDgzMjM2Njk0MyAzLjMzNTU3MTM2NDAwNDg2M2UtMDYgMTYuNDk5NzAwNTQ2MjY0NjUgMy4zMzU1NzEzNjQwMDQ4NjNlLTA2IEMgMjUuNjEzMTAwMDUxODc5ODggMy4zMzU1NzEzNjQwMDQ4NjNlLTA2IDMzLjAwMDMwMTM2MTA4Mzk4IDcuMzg3MjAzMjE2NTUyNzM0IDMzLjAwMDMwMTM2MTA4Mzk4IDE2LjQ5OTcwMjQ1MzYxMzI4IEMgMzMuMDAwMzAxMzYxMDgzOTggMjIuMjk2MjUzMjA0MzQ1NyAzMC4wMTIyODkwNDcyNDEyMSAyNy4zOTQwNTI1MDU0OTMxNiAyNS40OTE4NzY2MDIxNzI4NSAzMC4zMzcyNTM1NzA1NTY2NCBMIDI4Ljc3OTMwMDY4OTY5NzI3IDM2LjAzMTUwMTc3MDAxOTUzIEMgMjkuNjA4MjAwMDczMjQyMTkgMzcuNDY2MTAyNjAwMDk3NjYgMjkuMTE2ODAwMzA4MjI3NTQgMzkuMzAxMjA0NjgxMzk2NDggMjcuNjgxMzAxMTE2OTQzMzYgNDAuMTMwMTA0MDY0OTQxNDEgQyAyNy4yMDkwODczNzE4MjYxNyA0MC40MDI2NTI3NDA0Nzg1MiAyNi42OTMzNDk4MzgyNTY4NCA0MC41MzIyNDE4MjEyODkwNiAyNi4xODQ1Mzc4ODc1NzMyNCA0MC41MzIyNjQ3MDk0NzI2NiBaIgogICAgICAgICAgICBzdHJva2U9Im5vbmUiIGZpbGw9IiNmZmYiIC8+CiAgICA8L2c+CiAgICA8dGV4dCBpZD0iTVVfIiBkYXRhLW5hbWU9Ik1VICIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA0MykiIGZpbGw9IiNmZmYiIGZvbnQtc2l6ZT0iNDQiCiAgICAgICAgZm9udC1mYW1pbHk9IkxhdG8tQm9sZCwgTGF0byIgZm9udC13ZWlnaHQ9IjcwMCI+CiAgICAgICAgPHRzcGFuIHg9IjAiIHk9IjAiPk1VPC90c3Bhbj4KICAgIDwvdGV4dD4KICAgIDx0ZXh0IGlkPSJlbCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTA4IDQzKSIgZmlsbD0iI2ZmZiIgZm9udC1zaXplPSI0NCIKICAgICAgICBmb250LWZhbWlseT0iTGF0by1Cb2xkLCBMYXRvIiBmb250LXdlaWdodD0iNzAwIj4KICAgICAgICA8dHNwYW4geD0iMCIgeT0iMCI+RUw8L3RzcGFuPgogICAgPC90ZXh0Pgo8L3N2Zz4K
`

### doctor --verbose

`
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on macOS 11.2.1 20D74 darwin-x64, locale fr-FR)
    • Flutter version 1.26.0-17.5.pre at /Users/fahembelili/Development/flutter
    • Framework revision 1fe38dcb5f (5 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/fahembelili/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/fahembelili/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
Process finished with exit code 0
`

**Comment by helloplayer1** [comment]
I did run into the same Issue. :/

**Comment by BeliliFahem** [comment]
@helloplayer1 
I've resoved the problem by using the package that is used internaly by `web_svg`: 
`flutter_svg: 0.20.0-nullsafety.3`

**Comment by jpeiffer** [comment]
Should be fixed with this:
https://pub.dev/packages/websafe_svg/versions/2.0.0-nullsafety.0

Unfortunately, it has to stay a pre-release version until `flutter_svg` releases Null Safety on Stable too.

Please let me know if that's not the case and I'll take a closer look.
