### ISSUE TITLE
Any plans to release null safety support

### ISSUE THREAD

**Issue by venkata-reddy-dev** [peiffer-innovations/websafe_svg#18]
[migration guide ](https://dart.dev/null-safety/migration-guide)

**Comment by venkata-reddy-dev** [comment]
here is pull request #20

**Comment by jpeiffer** [comment]
Thanks.  There's actually a `nullsafety` branch already available that you can reference from Git.  There's some significant Flutter 2 issues on the web though that I want to address before I do a true release.

**Comment by jpeiffer** [comment]
Actually, it seems I made the branch but never pushed (doh!!!).  Merged yours, thanks for the contribution.  I'll post it in a release hopefully later tonight when I resolve the CanvisKit vs HtmlKit issue on Flutter 2.
