### ISSUE TITLE
websafe_svg does not work in flutter web 2.0

### ISSUE THREAD

**Issue by ghost** [peiffer-innovations/websafe_svg#19]
Hi,
If I run the app in a mobile emulator it works perfectly, however if I run the app in web mode the icons are not shown, only a rectangle with an x inside is shown.

**In debug console:**
Exception caught by image resource service
Failed to decode image data.
Image source: data:image/svg+xml;base64,PHN2Z...................................

Flutter 2.1.0-11.0.pre.145 channel master
Dart 2.13.0

Please is there a solution for this problem.
Thanks a lot. 
Regards,
Jose

**Comment by jjgumucio** [comment]
I confirm this bug...

**Comment by srvstvnhl** [comment]
Did you find any other way to display the svg images in the flutter web?

**Comment by CodingSoot** [comment]
Same issue.

**Comment by Mecil9** [comment]
Same +1

════════ Exception caught by image resource service ════════════════════════════
The following ImageCodecException was thrown resolving an image codec:
Failed to decode image data.
Image source: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIyLjEuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAyNTYgMjA3LjYiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDI1NiAyMDcuNjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLmNvbW1lbnQtMHtmaWxsOm5vbmU7c3Ryb2tlOiNGRkZGRkY7fQo8L3N0eWxlPgo8cGF0aCBjbGFzcz0iY29tbWVudC0wIGZpbGwtbm9uZSBzdHJva2Utd2hpdGUiIHN0cm9rZS13aWR0aD0iMyIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiBzdHJva2Utb3BhY2l0eT0iMC41IiBzdHJva2UtZGFzaGFycmF5PSIxMCIgZD0iTTEuNSwxNzJWNy41YzAtMy4zLDMuMy02LDcuMy02aDIzOC42YzMuOSwwLDcuMSwyLjYsNy4xLDUuOHYxNjRjMCwzLjYtMy41LDYuNS03LjksNi41SDYyLjQKCWMtMywwLTUuNiwxLjQtNi44LDMuN2wtMjIsMjIuNmwtMC4yLTIyLjRjLTEuMS0yLjMtMy44LTMuOS02LjgtMy45SDguNkM0LjcsMTc3LjgsMS41LDE3NS4yLDEuNSwxNzJ6Ii8+Cjwvc3ZnPgo=

**Comment by jpeiffer** [comment]
Have you tried using `flutter_svg` in the pre-release?  I've had some success with that.  This appears to be related to the canvas vs HTML based rendering.  HTML based works, canvas does not.

**Comment by Mecil9** [comment]
using flutter run -d chrome --web-renderer html, it's displayed , ok
but using vscode debug model like this launch.json file config don't display svg:
      "name": "Flutter",
      "type": "dart",
      "request": "launch",
      "program": "lib/main.dart",
      "args": ["--web-renderer html"]

**Comment by jpeiffer** [comment]
Fixed:
https://pub.dev/packages/websafe_svg/versions/2.0.0-nullsafety.0

Unfortunately, it has to stay a pre-release version until `flutter_svg` releases Null Safety on Stable too.
