### ISSUE TITLE
Overflow on channel: flutter/mousecursor

### ISSUE THREAD

**Issue by raycherr** [peiffer-innovations/websafe_svg#2]
`Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.`

When trying to display an svg on flutter web (as shown below) the error above occurs.

`SizedBox(height: 350, child: WebsafeSvg.asset('assets/undraw_warning_cyit.svg')),`

Edit to include flutter doctor -v

> [√] Flutter (Channel master, 1.19.0-2.0.pre.22, on Microsoft Windows [Version 10.0.18362.778], locale en-SG)
>     • Flutter version 1.19.0-2.0.pre.22 at C:\src\flutter
>     • Framework revision 2f993d70c1 (12 hours ago), 2020-05-12 13:44:02 -0700
>     • Engine revision 156970a248
>     • Dart version 2.9.0 (build 2.9.0-8.0.dev 4e520824f5)
> 
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\rachel\AppData\Local\Android\sdk
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 44.0.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.45.0)
>     • VS Code at C:\Users\rachel\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.10.1
> 
> [√] Connected device (2 available)
>     • Web Server • web-server • web-javascript • Flutter Tools
>     • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

**Comment by jpeiffer** [comment]
This plugin doesn't even utilize the mousecursor channel.  I believe this is an unrelated issue and am closing.

If you can provide a complete example app, I can try to investigate further.
