### ISSUE TITLE
WebsafeSvg.string error

### ISSUE THREAD

**Issue by rupamking1** [peiffer-innovations/websafe_svg#21]
Image key: NetworkImage("data:image/svg+xml;base64,PHN2ZyBpZD0iQ2FwYV8xIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCA1MTIgNTEyIiBoZWlnaHQ9IjUxMiIgdmlld0JveD0iMCAwIDUxMiA1MTIiIHdpZHRoPSI1MTIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0ibTQ4MS43NTUgMTA5Ljc1NmMtMy4yMDktMTcuMzE1LTE4LjcwMy0yOS42NzgtMzYuMjk4LTI4Ljk2NC0zNS4wNTggMS40MjQtOTguNTY5IDEyLjA0My0xNzEuMTYyIDYxLjcyNSAxOC4zMzUgNDYuOTYyIDMxLjU4IDEwNy40MDIgMzEuNTggMTg0LjA3MSAwIDkyLjcyNy00My44NTUgMTU0LjQ1MS0xMDMuNDQzIDE3Mi4xNiA1NS42OSAxNi42NjQgMTIzLjA1Mi01Ljk0OCAxNzcuMjc2LTczLjkwNCAxMTUuMjk5LTE0NC40OTkgMTExLjY0MS0yNjMuMzIgMTAyLjA0Ny0zMTUuMDg4eiIgZmlsbD0iIzk5NGUzNyIvPjxwYXRoIGQ9Im0xNDIuNjgxIDE2LjY1YzEzLjMwOC0xMS41MzMgMzMuMTMtMTEuNTMzIDQ2LjQzOCAwIDM5Ljc4OCAzNC40ODIgMTE2Ljc1NyAxMjUuMDc3IDExNi43NTcgMzA5LjkzOC0uMDAxIDExMC44NTEtNjIuNjcgMTc3LjQxMi0xMzkuOTc2IDE3Ny40MTJzLTEzOS45NzUtNjYuNTYxLTEzOS45NzUtMTc3LjQxMmMtLjAwMS0xODQuODYxIDc2Ljk2OC0yNzUuNDU2IDExNi43NTYtMzA5LjkzOHoiIGZpbGw9IiNjYzYyNGUiLz48cGF0aCBkPSJtMzA1Ljg3NSAzMjYuNTg4YzAgOTIuNzI3LTQzLjg1NSAxNTQuNDUxLTEwMy40NDMgMTcyLjE2IDkuODQ3IDIuOTQ3IDIwLjA2MSA0LjY1OSAzMC41IDUuMTE2IDU0LjI3OC0yMi43MTggOTIuOTIxLTgzLjM5OSA5Mi45MjEtMTcxLjM5NyAwLTg0LjcwMy0xNS44MTQtMTUwLjAzLTM2LjkyMy0xOTkuNTIxLTQuODMzIDMuMDE5LTkuNzEyIDYuMjAyLTE0LjYzNSA5LjU3MSAxOC4zMzUgNDYuOTYyIDMxLjU4IDEwNy40MDIgMzEuNTggMTg0LjA3MXoiIGZpbGw9IiM4YzQ1MzQiLz48cGF0aCBkPSJtMTg5LjExOCAxNi42NWMtOS4wODUtNy44NzQtMjEuMjA2LTEwLjM2OC0zMi4yMTktNy40OSA1LjExOCAxLjMzNyA5Ljk5NiAzLjgzMSAxNC4yMTkgNy40OSAzOS43ODggMzQuNDgyIDExNi43NTcgMTI1LjA3NyAxMTYuNzU3IDMwOS45MzggMCAxMDYuNTE1LTU3Ljg2NSAxNzIuMTI0LTEzMC45NzUgMTc3LjA5NiAyLjk3Ny4yMDIgNS45NzYuMzE2IDkgLjMxNiA3Ny4zMDYgMCAxMzkuOTc1LTY2LjU2MSAxMzkuOTc1LTE3Ny40MTIgMC0xODQuODYxLTc2Ljk2OS0yNzUuNDU2LTExNi43NTctMzA5LjkzOHoiIGZpbGw9IiNiYzU3NGEiLz48cGF0aCBkPSJtNDg5LjY3IDEwOC4wMDRjLTIuOTA4LTE1LjY5MS0xNC43NDctMjguNzMxLTI5Ljk4NS0zMy4zNjMtNC41NTMtMS4zODQtOS4zMzMtMS45OTgtMTQuMDg4LTEuODA1LTMxLjg5MyAxLjI5NS05NS4yMDMgMTAuNjYyLTE2Ny43MjIgNTcuOTg3LTIuNzMtNi41MzMtNS42MDctMTIuOTUyLTguNjQ4LTE5LjIzOS0yNC43MzYtNTEuMTQxLTU0LjYwMy04My4yNjEtNzUuMzA0LTEwMS4yLTExLjgyOS0xMC4yNTItMjkuMDUxLTEzLjE2My00My42NTMtNy42MTItNC42NDYgMS43NjYtOC45NzcgNC4zNTYtMTIuNzMzIDcuNjExLTI0LjIxNyAyMC45ODgtNTguNTAzIDU5LjA3LTg0LjMxOCAxMjEuMzAyLTEuNTkgMy44MzQuMjI5IDguMjMyIDQuMDYzIDkuODIzIDMuODM0IDEuNTg4IDguMjMyLS4yMjggOS44MjMtNC4wNjMgMjAuNjE3LTQ5LjcwMSA0Ni43MzktODMuMTY1IDY4LjE4NS0xMDQuNDYxLTkuMjY3IDE4LjcyMS0xOS43MzUgNDQuODYxLTI4Ljg3NCA3OS45OC0xNS43MDkgNjAuMzctMjMuNjc0IDEzMi4yNzUtMjMuNjc0IDIxMy43MTggMCA1NC4xMDEgNy44NyAxMDAuMzA5IDIyLjc1OSAxMzMuNjI4IDUuMTAzIDExLjQyIDEwLjk2OSAyMS4wODEgMTcuNDM4IDI4Ljg0OS0xOS4yNzctNy4zNjUtMzYuNTctMTkuOC01MC42MjItMzYuNzE4LTI1Ljc0NS0zMC45OTYtMzkuMzUzLTc0LjQ4My0zOS4zNTMtMTI1Ljc1OSAwLTU5LjQ0OCA4LjEwNi0xMTQuMDMyIDI0LjA5Mi0xNjIuMjM0IDEuMzA2LTMuOTQtLjgyOS04LjE5NC00Ljc2OC05LjUtMy45NDctMS4zMDctOC4xOTUuODI4LTkuNTAxIDQuNzY4LTE2LjQ5MiA0OS43MzEtMjQuODU1IDEwNS45MDctMjQuODU1IDE2Ni45NjYgMCA1NC44MjggMTQuODA4IDEwMS42MzYgNDIuODIyIDEzNS4zNjQgMjYuNzU2IDMyLjIxMyA2NC4wMzggNDkuOTU0IDEwNC45NzYgNDkuOTU0IDEyLjYyNyAwIDI0LjkwMy0xLjY5MyAzNi42MzItNC45NzIgMTEuNzU1IDMuMjk4IDIzLjg5NCA0Ljk2MyAzNi4yMjQgNC45NjMgMTguNDU4IDAgMzcuMzMtMy42ODQgNTUuODk5LTExLjAxIDMzLjA2OC0xMy4wNDYgNjQuNjczLTM3LjY0NSA5MS4zOTktNzEuMTM5IDIzLjE5MS0yOS4wNjUgNDIuOTktNTguODgyIDU4Ljg0Ni04OC42MjQgMS45NTItMy42NjMuNTY3LTguMjE2LTMuMDk3LTEwLjE2OS0zLjY2My0xLjk1My04LjIxNi0uNTY3LTEwLjE2OSAzLjA5Ny0xNS40MjMgMjguOTMxLTM0LjcxMyA1Ny45NzQtNTcuMzMxIDg2LjMyLTI1LjA4OSAzMS40NDItNTQuNTM5IDU0LjQ0OC04NS4xNjUgNjYuNTMxLTIwLjE3MiA3Ljk1Ny00MC42NiAxMS4xNTUtNjAuMzU2IDkuNTQyIDE1Ljc1Ny04LjM0NSAzMC4wMDMtMTkuOTM1IDQyLjA5NS0zNC40OTMgNC40MTMtNS4zMTMgOC40OTctMTAuOTUyIDEyLjI0OS0xNi44OTUgMTcuNTMyLTE1LjQ5NSAzNS4xMTItMzQuMjM1IDUyLjI2Ny01NS43MzMgNTAuNzk3LTYzLjY2MSA4OS40MTktMTI0LjgzNCAxMTQuNzkzLTE4MS44MiAxNC43NDgtMzMuMTIxIDIyLjg2OC02MC4wNjUgMjcuMzA0LTgwLjQ3MSA0LjM1MSAzOC4yNTcgMi44MjUgMTAyLjE1OC0zMi43NTcgMTgwLjQ4NS0xLjU4NiAzLjQ4OS0uMjE0IDcuNzMgMy4xMTIgOS42MzMgMy43OTQgMi4xNyA4Ljc3LjU1NyAxMC41NzQtMy40MTUgNDIuOTktOTQuNjM2IDM4LjEzOC0xNjkuNTc3IDMxLjQyMS0yMDUuODI2em0tMTg5LjE2MSA5NC40NjFjNzEuNjc1LTY5LjkzNiAxMjYuMTc0LTk3LjE1OSAxNTMuODIxLTEwNy40MjRsLTE0Mi45NDYgMTc5LjE0NmMtMi4wOTUtMjQuOTY3LTUuNzMtNDguODkzLTEwLjg3NS03MS43MjJ6bTEyOS4xMDQtMTEzLjMyNWMtNTIuNDE2IDI0LjQ2OS0xMDIuMjk4IDY2Ljk3OS0xMzMuMjM1IDk2LjQzNi0zLjY5Mi0xMy45MzUtNy45ODEtMjcuNDI5LTEyLjg1NS00MC40NzIgNTkuNTM1LTM5LjUgMTEyLjUzMy01Mi4yMDcgMTQ2LjA5LTU1Ljk2NHptLTMzMS44MzcgMjM3LjU0MmMwLTgwLjE2NyA3LjgwMi0xNTAuNzk5IDIzLjE4OS0yMDkuOTMyIDEyLjIyNC00Ni45OCAyNi43NTMtNzcuMDI3IDM3LjI0OS05NC40NTR2NDczLjczMmMtMTQuNzkxLTMuNjg0LTI4LjQyNC0xOC4yMTQtMzguOTg3LTQxLjg1MS0xNC4wMzQtMzEuNDA1LTIxLjQ1MS03NS40OTItMjEuNDUxLTEyNy40OTV6bTE2MS4zNjcgMTI1Ljc1OWMtMTQuMDUzIDE2LjkxOS0zMS4zNDUgMjkuMzUzLTUwLjYyMyAzNi43MTggNi40NjktNy43NjggMTIuMzM1LTE3LjQyOSAxNy40MzktMjguODQ5IDE0Ljg4OS0zMy4zMTkgMjIuNzU5LTc5LjUyNyAyMi43NTktMTMzLjYyOCAwLTQuMTUxLTMuMzY1LTcuNTE3LTcuNTE2LTcuNTE3LTQuMTUyIDAtNy41MTYgMy4zNjUtNy41MTYgNy41MTcgMCA1Mi4wMDQtNy40MTggOTYuMDktMjEuNDUgMTI3LjQ5NS0xMC41NjMgMjMuNjM3LTI0LjE5NyAzOC4xNjYtMzguOTg4IDQxLjg1MXYtNDczLjczNWMyMS4wMzYgMzQuODkyIDU1LjMzIDExNC44NTEgNTkuOTMgMjY5LjU5NC4xMjQgNC4xNDkgMy42MjQgNy40MjggNy43MzcgNy4yOSA0LjE1LS4xMjMgNy40MTQtMy41ODcgNy4yOS03LjczNy00LjAyNy0xMzUuNDQ0LTMwLjY5OS0yMTUuNDY5LTUxLjk5NC0yNTguNDEgMTguMTggMTguMDg0IDQwLjM4MSA0NS42MDQgNTkuNDgzIDg1LjA5OSAyOC40MDMgNTguNzIzIDQyLjgwNCAxMjguODkgNDIuODA0IDIwOC41NTMtLjAwMSA1MS4yNzYtMTMuNjA5IDk0Ljc2My0zOS4zNTUgMTI1Ljc1OXptMTc3LjE0LTI1MC45NThjLTI0Ljg1NSA1NS44MTktNjIuODEgMTE1Ljg5Ni0xMTIuODExIDE3OC41NTktNy4yNzggOS4xMjEtMTQuNjI3IDE3LjcxOC0yMi4wMDUgMjUuNzU5IDcuOTYtMjMuNjY1IDEyLjA2My01MC4yOCAxMi4wNjMtNzkuMTE4IDAtMTAuMjItLjIzMi0yMC4yOTItLjY5NS0zMC4yMWwxNTMuMjQ0LTE5Mi4wNTJjLTIuNjY1IDIwLjE2Ny0xMC4wNSA1Mi43MTQtMjkuNzk2IDk3LjA2MnoiLz48L3N2Zz4=", scale: 1)
════════════════════════════════════════════════════════════════════════════════

**Comment by jpeiffer** [comment]
What is the error you're seeing?

**Comment by rupamking1** [comment]
I am trying to use string method, but I got error please check it & fix it.

**Comment by jpeiffer** [comment]
Closing as "not enough info provided"
