### ISSUE TITLE
pub get fiailed , 2.0version

### ISSUE THREAD

**Issue by Mecil9** [peiffer-innovations/websafe_svg#22]
tips:
Because websafe_svg >=2.0.0-nullsafety.0 depends on http ^0.13.0 which depends on http_parser ^4.0.0, websafe_svg >=2.0.0-nullsafety.0 requires http_parser ^4.0.0.

And because dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0 and no versions of dio match >3.0.10 <4.0.0, websafe_svg >=2.0.0-nullsafety.0 is incompatible with dio ^3.0.10.

?how to fix it? pls

**Comment by jpeiffer** [comment]
It sounds like your issue is with `dio`.  Upgrading to version 4.0.0 of that library will likely solve your problem.
