### ISSUE TITLE
Style element is not implemented

### ISSUE THREAD

**Issue by Katekko** [peiffer-innovations/websafe_svg#5]
![image](https://user-images.githubusercontent.com/13632735/86932810-35888b80-c110-11ea-8736-f8655c08ec1f.png)

Any solution?

**Comment by jpeiffer** [comment]
This is actually an issue with the `flutter_svg` base library that this uses for Android and iOS.  Please open an issue here: https://github.com/dnfield/flutter_svg

That said, running https://github.com/RazrFalcon/svgcleaner against your SVGs will help, and also improve your performance.
