### ISSUE TITLE
SVG Stack Alignment

### ISSUE THREAD

**Issue by rupamking1** [peiffer-innovations/websafe_svg#9]
SVG Align widget Alignment is not working on Stack.
Please fix it.

class TestClass extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;

    return Container(
      color: Colors.white,
        child: Stack(
          children: [
            Align(
              alignment: Alignment.bottomCenter,
              child: WebsafeSvg.asset('assets/Menu.svg',
                  width: width, fit: BoxFit.contain),
            ),
          ],
        ),
      
    );
  }
}

**Comment by jpeiffer** [comment]
Please provide a working example showing the issue.

**Comment by rupamking1** [comment]
`class TestClass extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;

    return Container(
      color: Colors.white,
        child: Stack(
          children: [
            Align(
              alignment: Alignment.bottomCenter,
              child: WebsafeSvg.asset('assets/Menu.svg',
                  width: width, fit: BoxFit.contain),
            ),
          ],
        ),
      
    );
  }
}`

**Comment by jpeiffer** [comment]
Can you provide a full example?

For instance, is the issue Android, iOS, Desktop, Web, etc?  Ideally, a repo with the issue would be perfect.

Also, what version of Flutter is being used?

**Comment by rupamking1** [comment]
use your SVG plugin in a 'stack - align' then you can find this problem ? 
But I solved my problem.

Question-
1) can I able to use your plugin in desktop or Mac ?

**Comment by jpeiffer** [comment]
That's a better question for the https://pub.dev/packages/flutter_svg project, but I believe the answer is yes.

This project utilizes the `flutter_svg` project for "dart:io" based platforms, such as Desktop, Android and iOS.  So support on those ultimately depends on whether that project supports them.
